[package]
name = "rust-shamir"
version = "0.1.0"
authors = ["avahowell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"

[dependencies.zeroize]
features = ["zeroize_derive"]
version = "1.1.0"